### ISSUE TITLE
This library broke the entire RN gesture responder system on android

### ISSUE THREAD

**Issue by gaodeng** [expo/react-native-appearance#22] opened 2019-11-25 15:12 UTC
demo video
https://youtu.be/K6EdDVG05UM
Please pay attention to the change of the button highlight status when scrolling.

**Comment by gaodeng** [comment] 2019-11-25 15:22
here is the minimal code example that reproduces the problem

https://github.com/gaodeng/react-native-appearance-bug

**Comment by brentvatne** [comment] 2019-11-26 19:28
can you show me what it is supposed to look like in a video as well?

**Comment by gaodeng** [comment] 2019-11-27 01:47
@brentvatne 
You can reproduce the bug as follows
Scroll when pressed on a button in scrollview
1. Need to scroll **longer** than normal to cancel button highlighting
2. First scroll up a distance, the button is canceled highlighting, and then scroll back down, you will find that the button is highlighted **again** . If you lift your finger at this time,  the OnPress of the button is triggered

These behaviors will cause accidental tap issue

**Comment by brentvatne** [comment] 2019-11-27 18:16
thanks, i believe i know what the issue is

**Comment by brentvatne** [comment] 2019-11-27 18:37
this should be resolved in 0.2.4

**Closed as completed by brentvatne** 2019-11-27 18:37 UTC

**Comment by gaodeng** [comment] 2019-11-28 02:06
thanks 🙏🙏🙏
