### ISSUE TITLE
useColorScheme only updates when putting the app into the background and then foreground.

### ISSUE THREAD

**Issue by francisleigh** [expo/react-native-appearance#53] opened 2020-07-13 20:46 UTC
On my Android device, when i change the system theme via the pull-down menu i have to put my app into the background and then foreground in order to see the `Appearance ~> useColorScheme` API update.

Is this expected behaviour? 

```
function Root() {
    const scheme = useColorScheme();
    useEffect(() => {
        Appearance.addChangeListener((appearance) => {
            console.log("appearance", appearance);
        })
    }, []);
    console.log("scheme", scheme);

    return (
        <ThemeProvider theme={scheme === "dark" ? Theme.dark : Theme.default}>
            <NavigationContainer theme={scheme === "dark" ? Theme.dark : Theme.default}>
                <SplashScreen>
                    <AuthView />
                </SplashScreen>
            </NavigationContainer>
        </ThemeProvider>
    );
}
...
function App() {
    return (
        <AppearanceProvider>
              <Root />
        </AppearanceProvider>
    );
}
```

`"scheme"` & `"appearance"` logs only fire when the App comes into the foreground from being in the background when i am expecting the logs to fire as soon as the system theme is changed.

**Comment by outaTiME** [comment] 2020-10-26 17:18
Yup, something similar here on iOS with SDK39 when app background and then foreground.

@brentvatne is something similar to what was reported here? https://github.com/facebook/react-native/issues/28525

Thanks !!!

**Comment by brentvatne** [comment] 2020-10-26 20:35
can someone share a mcve? https://stackoverflow.com/help/mcve

**Comment by outaTiME** [comment] 2020-10-26 21:24
Sure, using this minimal example, with `"userInterfaceStyle": "automatic"` on app.json the logs shows the `colorScheme` goes to light and then go back dark (initial).

```js
import * as React from 'react';
import { StyleSheet, View, Text, Button } from 'react-native';
import { Appearance, AppearanceProvider, useColorScheme } from 'react-native-appearance';
import { StatusBar } from 'expo-status-bar';

export default () => {
  const colorScheme = useColorScheme();
  console.log('>>> colorScheme', colorScheme);
  const isDark = colorScheme === 'dark';
  return (
    <AppearanceProvider>
      <StatusBar style="auto" animated />
      <View style={{ flex: 1, backgroundColor: isDark ? '#333' : '#f1f1f1' }} />
    </AppearanceProvider>
  );
};
```

```
>>> colorScheme dark
>>> colorScheme light
>>> colorScheme dark
>>> colorScheme dark
>>> colorScheme light
>>> colorScheme dark
```

in the log above each of the light entries means that the application goes into background, and goes back to dark when it returns to foreground.

in complex structures this possibly generates unnecessary redrawings (as is the case of the image reported in the issue: https://github.com/expo/expo/issues/10815)

**Comment by outaTiME** [comment] 2020-10-26 22:11
@brentvatne as I put in the issue https://github.com/expo/expo/issues/10815 in my case this only happens in iOS as well on simulator (client) and standalone

**Comment by sayo96** [comment] 2020-12-12 09:40
@brentvatne Is there any fix for this issue?

**Comment by brentvatne** [comment] 2020-12-18 23:07
@sayo96 - as far as i know this is not an issue. please share a reproducible example. @outaTiME is referring to a separate issue about updating the color scheme *too often*, rather than what the title of this issue says.

![Screen Recording 2020-12-18 at 3 11 06 PM](https://user-images.githubusercontent.com/90494/102669599-e1b0b280-4143-11eb-8950-83fe1e88cb93.gif)

![Screen Recording 2020-12-18 at 3 15 16 PM](https://user-images.githubusercontent.com/90494/102669895-03119e80-4144-11eb-8b60-41744c8ee37c.gif)

this is just from copying the example above, setting `"userInterfaceStyle": "automatic"`, and running the project in sdk 40.

so i'll close the issue since nobody has been able to post a reproducible example

**Closed as completed** 2020-12-18 23:17 UTC

**Comment by outaTiME** [comment] 2020-12-18 23:35
hi @brentvatne, 
be careful, this error is related to this issue https://github.com/expo/expo/issues/10815 and is not related to the multiple changes of the color scheme, but rather to the behavior of the scheme when it goes background and returns to foreground (as seen in the image of that referenced error).

If the color scheme change occurs with the app in foregraund everything works perfectly (as seen in your example) and again this is something only from IOS.

**Comment by brentvatne** [comment] 2020-12-19 00:08
@outaTiME - from the issue description:

> On my Android device, when i change the system theme via the pull-down menu i have to put my app into the background and then foreground in order to see the Appearance ~> useColorScheme API update.

as shown on my video recording in previous comment, i can't reproduce this

i acknowledge https://github.com/expo/expo/issues/10815 but i don't think it's related to this issue

**Comment by outaTiME** [comment] 2020-12-19 00:15
> @outaTiME - from the issue description:
> 
> > On my Android device, when i change the system theme via the pull-down menu i have to put my app into the background and then foreground in order to see the Appearance ~> useColorScheme API update.
> 
> as shown on my video recording in previous comment, i can't reproduce this
> 
> i acknowledge [expo/expo#10815](https://github.com/expo/expo/issues/10815) but i don't think it's related to this issue

Yes, but in an example that you built (on iOS) the app is always in the foreground, the problem is when you leave the foreground and go to the background and then return to the foreground again, for some reason for a moment the `useColorTheme` returns the opposite value to the selected scheme.

Here is the clear example:

![](https://user-images.githubusercontent.com/140472/97225008-c7e09800-17b0-11eb-95d4-c2e10f63c1ca.gif)

and again this happens using `useColorTheme` of `react-native-appearance` and also the native one and I also tried with the SDK40 and the same problem.

**Comment by outaTiME** [comment] 2020-12-19 00:17
btw, you could try the mwe that I build and see the logs, and there you will really see the behavior described above:

https://github.com/expo/react-native-appearance/issues/53#issuecomment-716832138

**Comment by brentvatne** [comment] 2020-12-19 02:05
@outaTiME - yeah that's a separate issue though. this issue is about "useColorScheme only updates when putting the app into the background and then foreground." which is not what you're talking about.

what you are describing is totally covered by this issue: https://github.com/expo/expo/issues/10815

**Comment by outaTiME** [comment] 2020-12-19 15:51
yup @brentvatne, there is a fine line between both errors they are quite similar and it could give confusion
